/*
 * Forms submission
 * API work with forms
 *
 * OpenAPI spec version: 1.0.0
 * Contact: CARNEIN@allianz.fr
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * BackupHabitation
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-08-08T08:35:16.049Z")
public class BackupHabitation {
  @SerializedName("residence")
  private String residence = null;

  @SerializedName("type")
  private String type = null;

  @SerializedName("rooms")
  private BigDecimal rooms = null;

  public BackupHabitation residence(String residence) {
    this.residence = residence;
    return this;
  }

   /**
   * Residence
   * @return residence
  **/
  @ApiModelProperty(example = "Ma résidence secondaire", value = "Residence")
  public String getResidence() {
    return residence;
  }

  public void setResidence(String residence) {
    this.residence = residence;
  }

  public BackupHabitation type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Residence type
   * @return type
  **/
  @ApiModelProperty(example = "Appartement", value = "Residence type")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public BackupHabitation rooms(BigDecimal rooms) {
    this.rooms = rooms;
    return this;
  }

   /**
   * number of rooms
   * @return rooms
  **/
  @ApiModelProperty(example = "3.0", value = "number of rooms")
  public BigDecimal getRooms() {
    return rooms;
  }

  public void setRooms(BigDecimal rooms) {
    this.rooms = rooms;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BackupHabitation backupHabitation = (BackupHabitation) o;
    return Objects.equals(this.residence, backupHabitation.residence) &&
        Objects.equals(this.type, backupHabitation.type) &&
        Objects.equals(this.rooms, backupHabitation.rooms);
  }

  @Override
  public int hashCode() {
    return Objects.hash(residence, type, rooms);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BackupHabitation {\n");
    
    sb.append("    residence: ").append(toIndentedString(residence)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    rooms: ").append(toIndentedString(rooms)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

