/*
 * Forms submission
 * API work with forms
 *
 * OpenAPI spec version: 1.0.0
 * Contact: CARNEIN@allianz.fr
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * CNIL
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-08-08T08:35:16.049Z")
public class CNIL {
  @SerializedName("cnil")
  private Boolean cnil = null;

  public CNIL cnil(Boolean cnil) {
    this.cnil = cnil;
    return this;
  }

   /**
   * User acceptation to receive commercial offers
   * @return cnil
  **/
  @ApiModelProperty(example = "false", value = "User acceptation to receive commercial offers")
  public Boolean isCnil() {
    return cnil;
  }

  public void setCnil(Boolean cnil) {
    this.cnil = cnil;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CNIL CNIL = (CNIL) o;
    return Objects.equals(this.cnil, CNIL.cnil);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cnil);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CNIL {\n");
    
    sb.append("    cnil: ").append(toIndentedString(cnil)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

