/*
 * Forms submission
 * API work with forms
 *
 * OpenAPI spec version: 1.0.0
 * Contact: CARNEIN@allianz.fr
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.BackupHabitation;
import io.swagger.client.model.CNIL;
import io.swagger.client.model.Intermediary;
import io.swagger.client.model.Person;
import io.swagger.client.model.Tracking;
import java.io.IOException;

/**
 * BackupHabitationFields
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-08-08T08:34:11.196Z")
public class BackupHabitationFields {
  @SerializedName("person")
  private Person person = null;

  @SerializedName("intermediary")
  private Intermediary intermediary = null;

  @SerializedName("cnil")
  private CNIL cnil = null;

  @SerializedName("tracking")
  private Tracking tracking = null;

  @SerializedName("backupHabitation")
  private BackupHabitation backupHabitation = null;

  public BackupHabitationFields person(Person person) {
    this.person = person;
    return this;
  }

   /**
   * Get person
   * @return person
  **/
  @ApiModelProperty(value = "")
  public Person getPerson() {
    return person;
  }

  public void setPerson(Person person) {
    this.person = person;
  }

  public BackupHabitationFields intermediary(Intermediary intermediary) {
    this.intermediary = intermediary;
    return this;
  }

   /**
   * Get intermediary
   * @return intermediary
  **/
  @ApiModelProperty(value = "")
  public Intermediary getIntermediary() {
    return intermediary;
  }

  public void setIntermediary(Intermediary intermediary) {
    this.intermediary = intermediary;
  }

  public BackupHabitationFields cnil(CNIL cnil) {
    this.cnil = cnil;
    return this;
  }

   /**
   * Get cnil
   * @return cnil
  **/
  @ApiModelProperty(value = "")
  public CNIL getCnil() {
    return cnil;
  }

  public void setCnil(CNIL cnil) {
    this.cnil = cnil;
  }

  public BackupHabitationFields tracking(Tracking tracking) {
    this.tracking = tracking;
    return this;
  }

   /**
   * Get tracking
   * @return tracking
  **/
  @ApiModelProperty(value = "")
  public Tracking getTracking() {
    return tracking;
  }

  public void setTracking(Tracking tracking) {
    this.tracking = tracking;
  }

  public BackupHabitationFields backupHabitation(BackupHabitation backupHabitation) {
    this.backupHabitation = backupHabitation;
    return this;
  }

   /**
   * Get backupHabitation
   * @return backupHabitation
  **/
  @ApiModelProperty(value = "")
  public BackupHabitation getBackupHabitation() {
    return backupHabitation;
  }

  public void setBackupHabitation(BackupHabitation backupHabitation) {
    this.backupHabitation = backupHabitation;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BackupHabitationFields backupHabitationFields = (BackupHabitationFields) o;
    return Objects.equals(this.person, backupHabitationFields.person) &&
        Objects.equals(this.intermediary, backupHabitationFields.intermediary) &&
        Objects.equals(this.cnil, backupHabitationFields.cnil) &&
        Objects.equals(this.tracking, backupHabitationFields.tracking) &&
        Objects.equals(this.backupHabitation, backupHabitationFields.backupHabitation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(person, intermediary, cnil, tracking, backupHabitation);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BackupHabitationFields {\n");
    
    sb.append("    person: ").append(toIndentedString(person)).append("\n");
    sb.append("    intermediary: ").append(toIndentedString(intermediary)).append("\n");
    sb.append("    cnil: ").append(toIndentedString(cnil)).append("\n");
    sb.append("    tracking: ").append(toIndentedString(tracking)).append("\n");
    sb.append("    backupHabitation: ").append(toIndentedString(backupHabitation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

