swagger: "2.0"
info:
  $ref: ./info/forms.yaml
host: "forms.swagger.io"
basePath: "/v2"
tags:
- name: "forms"
  description: "Everything about forms"
  externalDocs:
    description: "Find out more"
    url: "https://srvconfluence/display/ONEMARK/APIs"
schemes:
- "https"
paths:
  $ref: ./paths/forms-path.yaml
defintiions:
  $ref: ./paths/forms-defintions.yaml

externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"